package com.thomasjbarrerasconsulting.faces.kotlin.facedetector

import com.thomasjbarrerasconsulting.faces.R
import com.thomasjbarrerasconsulting.faces.kotlin.FaceBreakApplication

class ClassifierText {
    companion object{
        fun get(label:String, genderClassifier: GenderClassifier? = null): String {
            val context = FaceBreakApplication.instance

            return when (label){
                "Central and South America"	->	context.getString(R.string.ancestry_central_and_south_america)
                "China"	->	context.getString(R.string.ancestry_china)
                "East Africa (Somalia, Kenya, Ethiopia, Eritrea)"	->	context.getString(R.string.ancestry_east_africa)
                "Eastern Europe (Poland, Czech Republic, Romania, Bulgaria, Russia)"	->	context.getString(R.string.ancestry_eastern_european)
                "England"	->	context.getString(R.string.ancestry_england)
                "Ireland, Scotland and Wales"	->	context.getString(R.string.ancestry_ireland)
                "Japan and Korea"	->	context.getString(R.string.ancestry_japan_and_korea)
                "North Africa and the Middle East"	->	context.getString(R.string.ancestry_north_africa)
                "North America"	->	context.getString(R.string.ancestry_north_america)
                "North India"	->	context.getString(R.string.ancestry_north_india)
                "Polynesia"	->	context.getString(R.string.ancestry_polynesia)
                "Scandinavia"	->	context.getString(R.string.ancestry_scandinavia)
                "South India"	->	context.getString(R.string.ancestry_south_india)
                "Southeast Asia (Vietnam, Cambodia, Thailand, Indonesia)"	->	context.getString(R.string.ancestry_southeast_asia)
                "Southern Europe (Spain, Italy, Greece and the Balkans)"	->	context.getString(R.string.ancestry_southern_europe)
                "West Africa (Nigeria, Ghana, Congo, Angola, Namibia)"	->	context.getString(R.string.ancestry_west_africa)
                "Western Europe (France and Germany)"	->	context.getString(R.string.ancestry_western_europe)
                "Adorable"	-> if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_adorable_masculine) else context.getString(R.string.character_adorable_feminine)
                "Angelic"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_angelic_masculine) else context.getString(R.string.character_angelic_feminine)
                "Beautiful"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_classically_beautiful_masculine) else context.getString(R.string.character_classically_beautiful_feminine)
                "Compassionate"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_compassionate_masculine) else context.getString(R.string.character_compassionate_feminine)
                "Creative"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_creative_masculine) else context.getString(R.string.character_creative_feminine)
                "Free Spirited"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_free_spirited_masculine) else context.getString(R.string.character_free_spirited_feminine)
                "Honest"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_honest_masculine) else context.getString(R.string.character_honest_feminine)
                "Kind"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_kind_masculine) else context.getString(R.string.character_kind_feminine)
                "Naturally Beautiful"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_naturally_beautiful_masculine) else context.getString(R.string.character_naturally_beautiful_feminine)
                "Passionate"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_passionate_masculine) else context.getString(R.string.character_passionate_feminine)
                "Resourceful"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_resourceful_masculine) else context.getString(R.string.character_resourceful_feminine)
                "Responsible"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_responsible_masculine) else context.getString(R.string.character_responsible_feminine)
                "Rugged"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_rugged_masculine) else context.getString(R.string.character_rugged_feminine)
                "Strong"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_strong_masculine) else context.getString(R.string.character_strong_feminine)
                "Virtuous"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_virtuous_masculine) else context.getString(R.string.character_virtuous_feminine)
                "Wise"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.character_wise_masculine) else context.getString(R.string.character_wise_feminine)
                "Bossy"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_bossy_masculine) else context.getString(R.string.flaw_bossy_feminine)
                "Confused"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_confused_masculine) else context.getString(R.string.flaw_confused_feminine)
                "Cranky"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_cantankerous_masculine) else context.getString(R.string.flaw_cantankerous_feminine)
                "Flirty"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_flirty_masculine) else context.getString(R.string.flaw_flirty_feminine)
                "Grumpy"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_grumpy_masculine) else context.getString(R.string.flaw_grumpy_feminine)
                "Impulsive"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_impulsive_masculine) else context.getString(R.string.flaw_impulsive_feminine)
                "Irritating"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_irritating_masculine) else context.getString(R.string.flaw_irritating_feminine)
                "Lazy"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_lazy_masculine) else context.getString(R.string.flaw_lazy_feminine)
                "Melodramatic"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_melodramatic_masculine) else context.getString(R.string.flaw_melodramatic_feminine)
                "Pompous"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_pompous_masculine) else context.getString(R.string.flaw_pompous_feminine)
                "Proud"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_proud_masculine) else context.getString(R.string.flaw_proud_feminine)
                "Rebellious"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_rebellious_masculine) else context.getString(R.string.flaw_rebellious_feminine)
                "Spoiled"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_spoiled_masculine) else context.getString(R.string.flaw_spoiled_feminine)
                "Timid"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_anxious_masculine) else context.getString(R.string.flaw_anxious_feminine)
                "Uninhibited"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_uninhibited_masculine) else context.getString(R.string.flaw_uninhibited_feminine)
                "Vain"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_vain_masculine) else context.getString(R.string.flaw_vain_feminine)
                "Wild"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.flaw_wild_masculine) else context.getString(R.string.flaw_wild_feminine)
                "Blue Eyes"	->	context.getString(R.string.eyecolor_blue_eyes)
                "Brown Eyes"	->	context.getString(R.string.eyecolor_brown_eyes)
                "Closed Eyes"	->	context.getString(R.string.eyecolor_closed_eyes)
                "Green Eyes"	->	context.getString(R.string.eyecolor_green_eyes)
                "Grey Eyes"	->	context.getString(R.string.eyecolor_grey_eyes)
                "Pure Blue Eyes"	->	context.getString(R.string.eyecolor_pure_blue)
                "Pure Brown Eyes"	->	context.getString(R.string.eyecolor_pure_brown)
                "Pure Green Eyes"	->	context.getString(R.string.eyecolor_pure_green)
                "Pure Grey Eyes"	->	context.getString(R.string.eyecolor_pure_grey)
                "Trace Blue Eyes"	->	context.getString(R.string.eyecolor_trace_blue)
                "Trace Brown Eyes"	->	context.getString(R.string.eyecolor_trace_brown)
                "Trace Green Eyes"	->	context.getString(R.string.eyecolor_trace_green)
                "Trace Grey Eyes"	->	context.getString(R.string.eyecolor_trace_grey)
                "Angry"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.emotion_angry_masculine) else context.getString(R.string.emotion_angry_feminine)
                "Disgusted"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.emotion_disgusted_masculine) else context.getString(R.string.emotion_disgusted_feminine)
                "Happy"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.emotion_happy_masculine) else context.getString(R.string.emotion_happy_feminine)
                "Sad"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.emotion_sad_masculine) else context.getString(R.string.emotion_sad_feminine)
                "Scared"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.emotion_scared_masculine) else context.getString(R.string.emotion_scared_feminine)
                "Serious"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.emotion_serious_masculine) else context.getString(R.string.emotion_serious_feminine)
                "Silly"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.emotion_silly_masculine) else context.getString(R.string.emotion_silly_feminine)
                "Stern"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.emotion_stern_masculine) else context.getString(R.string.emotion_stern_feminine)
                "Surprised"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.emotion_surprised_masculine) else context.getString(R.string.emotion_surprised_feminine)
                "Suspicious"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.emotion_suspicious_masculine) else context.getString(R.string.emotion_suspicious_feminine)
                "Male"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.gender_male_masculine) else context.getString(R.string.gender_male_feminine)
                "Female"	->	if (genderClassifier!!.isMaleOrGenderNeutral()) context.getString(R.string.gender_female_masculine) else context.getString(R.string.gender_female_feminine)
                "Diamond"	->	context.getString(R.string.faceshape_diamond)
                "Heart"	->	context.getString(R.string.faceshape_heart)
                "Oblong"	->	context.getString(R.string.faceshape_oblong)
                "Oval"	->	context.getString(R.string.faceshape_oval)
                "Pear"	->	context.getString(R.string.faceshape_pear)
                "Round"	->	context.getString(R.string.faceshape_round)
                "Square"	->	context.getString(R.string.faceshape_square)
                "Strong Diamond"	->	context.getString(R.string.faceshape_strong_diamond)
                "Strong Heart"	->	context.getString(R.string.faceshape_strong_heart)
                "Strong Oblong"	->	context.getString(R.string.faceshape_strong_oblong)
                "Strong Oval"	->	context.getString(R.string.faceshape_strong_oval)
                "Strong Pear"	->	context.getString(R.string.faceshape_strong_pear)
                "Strong Round"	->	context.getString(R.string.faceshape_strong_round)
                "Strong Square"	->	context.getString(R.string.faceshape_strong_square)
                "Very Strong Diamond"	->	context.getString(R.string.faceshape_very_strong_diamond)
                "Very Strong Heart"	->	context.getString(R.string.faceshape_very_strong_heart)
                "Very Strong Oblong"	->	context.getString(R.string.faceshape_very_strong_oblong)
                "Very Strong Oval"	->	context.getString(R.string.faceshape_very_strong_oval)
                "Very Strong Pear"	->	context.getString(R.string.faceshape_very_strong_pear)
                "Very Strong Round"	->	context.getString(R.string.faceshape_very_strong_round)
                "Very Strong Square"	->	context.getString(R.string.faceshape_very_strong_square)
                "Slightly Diamond"	->	context.getString(R.string.faceshape_slightly_diamond)
                "Slightly Heart"	->	context.getString(R.string.faceshape_slightly_heart)
                "Slightly Oblong"	->	context.getString(R.string.faceshape_slightly_oblong)
                "Slightly Oval"	->	context.getString(R.string.faceshape_slightly_oval)
                "Slightly Pear"	->	context.getString(R.string.faceshape_slightly_pear)
                "Slightly Round"	->	context.getString(R.string.faceshape_slightly_round)
                "Slightly Square"	->	context.getString(R.string.faceshape_slightly_square)
                "Unlike Diamond"	->	context.getString(R.string.faceshape_unlike_diamond)
                "Unlike Heart"	->	context.getString(R.string.faceshape_unlike_heart)
                "Unlike Oblong"	->	context.getString(R.string.faceshape_unlike_oblong)
                "Unlike Oval"	->	context.getString(R.string.faceshape_unlike_oval)
                "Unlike Pear"	->	context.getString(R.string.faceshape_unlike_pear)
                "Unlike Round"	->	context.getString(R.string.faceshape_unlike_round)
                "Unlike Square"	->	context.getString(R.string.faceshape_unlike_square)
                "Very Unlike Heart"	->	context.getString(R.string.faceshape_very_unlike_heart)
                "Very Unlike Oblong"	->	context.getString(R.string.faceshape_very_unlike_oblong)
                "Very Unlike Oval"	->	context.getString(R.string.faceshape_very_unlike_oval)
                "Very Unlike Pear"	->	context.getString(R.string.faceshape_very_unlike_pear)
                "Very Unlike Round"	->	context.getString(R.string.faceshape_very_unlike_round)
                "Very Unlike Square"	->	context.getString(R.string.faceshape_very_unlike_square)
                "Bald"	->	context.getString(R.string.haircolor_no_hair_detected)
                "Black"	->	context.getString(R.string.haircolor_black)
                "Blond"	->	context.getString(R.string.haircolor_blond)
                "Blue"	->	context.getString(R.string.haircolor_blue)
                "Brown"	->	context.getString(R.string.haircolor_brown)
                "Green"	->	context.getString(R.string.haircolor_green)
                "Grey"	->	context.getString(R.string.haircolor_grey)
                "Neon Red"	->	context.getString(R.string.haircolor_neon_red)
                "Orange"	->	context.getString(R.string.haircolor_orange)
                "Pink"	->	context.getString(R.string.haircolor_pink)
                "Purple"	->	context.getString(R.string.haircolor_purple)
                "Red"	->	context.getString(R.string.haircolor_red)
                "White"	->	context.getString(R.string.haircolor_white)
                "Yellow"	->	context.getString(R.string.haircolor_yellow)
                "Hairless" -> context.getString(R.string.hairstyle_hairless)
                "Afro"	->	context.getString(R.string.hairstyle_afro)
                "Bob"	->	context.getString(R.string.hairstyle_bob)
                "Braided Pig Tails"	->	context.getString(R.string.hairstyle_braided_pig_tails)
                "Braids"	->	context.getString(R.string.hairstyle_braids)
                "Buzz Cut"	->	context.getString(R.string.hairstyle_buzz_cut)
                "Curly"	->	context.getString(R.string.hairstyle_curly)
                "Hair Bun"	->	context.getString(R.string.hairstyle_hair_bun)
                "Head Covered"	->	context.getString(R.string.hairstyle_head_covered)
                "Long"	->	context.getString(R.string.hairstyle_long_hair)
                "Men's Medium"	->	context.getString(R.string.hairstyle_mens_medium)
                "Mohawk"	->	context.getString(R.string.hairstyle_mohawk)
                "Mullet"	->	context.getString(R.string.hairstyle_mullet)
                "Pig Tails"	->	context.getString(R.string.hairstyle_pig_tails)
                "Pixie"	->	context.getString(R.string.hairstyle_pixie)
                "Women's Medium"	->	context.getString(R.string.hairstyle_womens_medium)
                "Women's Short"	->	context.getString(R.string.hairstyle_womens_short)
                "Baseball Cap"	->	context.getString(R.string.physicalfeature_baseball_cap)
                "Clear"	->	context.getString(R.string.physicalfeature_clear)
                "Cowboy Hat"	->	context.getString(R.string.physicalfeature_cowboy_hat)
                "Hat"	->	context.getString(R.string.physicalfeature_hat)
                "Headscarf"	->	context.getString(R.string.physicalfeature_headscarf)
                "Medium Eyebrows"	->	context.getString(R.string.physicalfeature_medium_eyebrows)
                "No Eyebrows"	->	context.getString(R.string.physicalfeature_no_eyebrows)
                "Thick Eyebrows"	->	context.getString(R.string.physicalfeature_thick_eyebrows)
                "Thin Eyebrows"	->	context.getString(R.string.physicalfeature_thin_eyebrows)
                "Acne"	->	context.getString(R.string.physicalfeature_acne)
                "Beard"	->	context.getString(R.string.physicalfeature_beard)
                "Dark Lips"	->	context.getString(R.string.physicalfeature_dark_lips)
                "Dimples"	->	context.getString(R.string.physicalfeature_dimples)
                "Freckles"	->	context.getString(R.string.physicalfeature_freckles)
                "Full Lips"	->	context.getString(R.string.physicalfeature_full_lips)
                "Goatee"	->	context.getString(R.string.physicalfeature_goatee)
                "Mask"	->	context.getString(R.string.physicalfeature_mask)
                "Moustache"	->	context.getString(R.string.physicalfeature_moustache)
                "Pink Lips"	->	context.getString(R.string.physicalfeature_pink_lips)
                "Red Lips"	->	context.getString(R.string.physicalfeature_red_lips)
                "Stubble"	->	context.getString(R.string.physicalfeature_stubble)
                "Bindi"	->	context.getString(R.string.physicalfeature_bindi)
                "Earrings"	->	context.getString(R.string.physicalfeature_earrings)
                "Glasses"	->	context.getString(R.string.physicalfeature_glasses)
                "Sunglasses"	->	context.getString(R.string.physicalfeature_sunglasses)

                else -> context.getString(R.string.faceshape_unknown)
            }
        }
    }
}